### ISSUE TITLE
Version problem in incorporating StyleGAN2 augment code

### ISSUE THREAD

**Issue by priyamp2309** [boschresearch/one-shot-synthesis#5]
While adding augment.py as told in instructions, an error comes up as -
symbolic_assert = torch.Assert # 1.7.0
AttributeError: module 'torch' has no attribute 'Assert'

This torch.Assert is available in torch 1.7.0 but OSGAN requirement is torch 1.6 for which when I updated torch to 1.7 it gave - ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/home/usd.local/priyam.pandey/anaconda3/envs/osmis/lib/python3.8/site-packages/typing_extensions.py)

This error is came up because it is not available in torch 1.7.

What can be done please help?
